version: '3'

services:
  sailing-assistant:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./.byaldi:/app/.byaldi
      - ./chroma_db:/app/chroma_db
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - LOG_LEVEL=INFO
      - CHROMA_HOST=localhost
      - CHROMA_PORT=8000
      - FORUM_COLLECTION=forum_content
      - VISUAL_INDEX_PATH=.byaldi
      - VISUAL_MODEL_NAME=vidore/colqwen2-v1.0
      - VISUAL_DEVICE=cpu
      - CHAINLIT_HOST=0.0.0.0
      - CHAINLIT_PORT=8080
      - CHAINLIT_AUTH_SECRET=${CHAINLIT_AUTH_SECRET:-your_secret_key_here}
    restart: unless-stopped 