services:
  sailing-assistant:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    command: chainlit run src/app.py --port 8000 --host 0.0.0.0
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./.byaldi:/app/.byaldi
      - ./chroma_db:/app/chroma_db
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - LOG_LEVEL=INFO
      - FORUM_COLLECTION=forum_content
      - VISUAL_INDEX_PATH=.byaldi
      - VISUAL_MODEL_NAME=vidore/colqwen2-v1.0
      - VISUAL_DEVICE=cuda
      - CHAINLIT_HOST=0.0.0.0
      - CHAINLIT_PORT=8000
      - PYTHONUNBUFFERED=1
      - CHAINLIT_AUTH_SECRET=${CHAINLIT_AUTH_SECRET:-your_secret_key_here}
      - PYTHONIOENCODING=utf-8
    restart: unless-stopped 