version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    image: sailing-assistant-gpu
    container_name: sailing-assistant-gpu
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./.byaldi:/app/.byaldi
      - ./data:/app/data
      - ./logs:/app/logs
      - ./chroma_db:/app/chroma_db
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - VISUAL_DEVICE=cuda
      - CUDA_VISIBLE_DEVICES=0
      - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:128
      - LOG_LEVEL=INFO
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 