name: sailing-assistant
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.12.31
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.15
  - pip=25.0
  - python=3.11.11
  - readline=8.2
  - setuptools=75.8.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - accelerate==1.4.0
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.4.6
      - aiohttp==3.11.12
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - anyio==4.8.0
      - asgiref==3.8.1
      - asyncer==0.0.7
      - attrs==25.1.0
      - backoff==2.2.1
      - bcrypt==4.2.1
      - bidict==0.23.1
      - build==1.2.2.post1
      - byaldi==0.0.7
      - cachetools==5.5.2
      - catalogue==2.0.10
      - certifi==2025.1.31
      - chainlit==2.2.1
      - charset-normalizer==3.4.1
      - chevron==0.14.0
      - chroma-hnswlib==0.7.6
      - chromadb==0.6.3
      - click==8.1.8
      - coloredlogs==15.0.1
      - colpali-engine==0.3.8
      - dataclasses-json==0.6.7
      - datasets==3.3.2
      - deprecated==1.2.18
      - dill==0.3.8
      - durationpy==0.9
      - eval-type-backport==0.2.2
      - fastapi==0.115.8
      - filelock==3.17.0
      - filetype==1.2.0
      - flatbuffers==25.2.10
      - frozenlist==1.5.0
      - fsspec==2024.12.0
      - google-ai-generativelanguage==0.6.15
      - google-api-core==2.24.1
      - google-api-python-client==2.161.0
      - google-auth==2.38.0
      - google-auth-httplib2==0.2.0
      - google-generativeai==0.8.4
      - googleapis-common-protos==1.68.0
      - gputil==1.4.0
      - grpcio==1.70.0
      - grpcio-status==1.70.0
      - h11==0.14.0
      - httpcore==1.0.7
      - httplib2==0.22.0
      - httptools==0.6.4
      - httpx==0.28.1
      - huggingface-hub==0.29.1
      - humanfriendly==10.0
      - idna==3.10
      - importlib-metadata==8.5.0
      - importlib-resources==6.5.2
      - jinja2==3.1.5
      - joblib==1.4.2
      - jsonlines==4.0.0
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - kubernetes==32.0.1
      - langchain==0.3.19
      - langchain-chroma==0.2.2
      - langchain-core==0.3.37
      - langchain-google-genai==2.0.10
      - langchain-huggingface==0.1.2
      - langchain-text-splitters==0.3.6
      - langgraph==0.2.74
      - langgraph-checkpoint==2.0.16
      - langgraph-sdk==0.1.53
      - langsmith==0.3.10
      - lazify==0.4.0
      - literalai==0.1.103
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - marshmallow==3.26.1
      - mdurl==0.1.2
      - ml-dtypes==0.5.1
      - mmh3==5.1.0
      - monotonic==1.6
      - mpmath==1.3.0
      - msgpack==1.1.0
      - mteb==1.6.35
      - multidict==6.1.0
      - multiprocess==0.70.16
      - mypy-extensions==1.0.0
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - ninja==1.11.1.3
      - numpy==1.26.4
      - oauthlib==3.2.2
      - onnxruntime==1.20.1
      - opentelemetry-api==1.29.0
      - opentelemetry-exporter-otlp==1.29.0
      - opentelemetry-exporter-otlp-proto-common==1.29.0
      - opentelemetry-exporter-otlp-proto-grpc==1.29.0
      - opentelemetry-exporter-otlp-proto-http==1.29.0
      - opentelemetry-instrumentation==0.50b0
      - opentelemetry-instrumentation-asgi==0.50b0
      - opentelemetry-instrumentation-fastapi==0.50b0
      - opentelemetry-proto==1.29.0
      - opentelemetry-sdk==1.29.0
      - opentelemetry-semantic-conventions==0.50b0
      - opentelemetry-util-http==0.50b0
      - orjson==3.10.15
      - overrides==7.7.0
      - packaging==24.2
      - pandas==2.2.3
      - pdf2image==1.17.0
      - peft==0.14.0
      - pillow==11.1.0
      - posthog==3.15.1
      - propcache==0.3.0
      - proto-plus==1.26.0
      - protobuf==5.29.3
      - psutil==7.0.0
      - pyarrow==19.0.1
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pygments==2.19.1
      - pyjwt==2.10.1
      - pyparsing==3.2.1
      - pypika==0.48.9
      - pyproject-hooks==1.2.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-engineio==4.11.2
      - python-multipart==0.0.18
      - python-socketio==5.12.1
      - pytz==2025.1
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - rich==13.9.4
      - rsa==4.9
      - safetensors==0.5.2
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - sentence-transformers==3.4.1
      - shellingham==1.5.4
      - simple-websocket==1.1.0
      - six==1.17.0
      - sniffio==1.3.1
      - sqlalchemy==2.0.38
      - srsly==2.5.1
      - starlette==0.41.3
      - sympy==1.13.1
      - syncer==2.0.3
      - tenacity==9.0.0
      - threadpoolctl==3.5.0
      - tokenizers==0.21.0
      - tomli==2.2.1
      - torch==2.6.0
      - tqdm==4.67.1
      - transformers==4.47.1
      - typer==0.15.1
      - typing-extensions==4.12.2
      - typing-inspect==0.9.0
      - tzdata==2025.1
      - uptrace==1.29.0
      - uritemplate==4.1.1
      - urllib3==2.3.0
      - uvicorn==0.34.0
      - uvloop==0.21.0
      - watchfiles==0.20.0
      - websocket-client==1.8.0
      - websockets==15.0
      - wrapt==1.17.2
      - wsproto==1.2.0
      - xxhash==3.5.0
      - yarl==1.18.3
      - zipp==3.21.0
      - zstandard==0.23.0
